[build]
  publish = "sources/client/dist"
  command = "yarn build:client"

[build.environment]
  VUE_APP_SOCKET_ENDPOINT = ""

[context.deploy-preview]
  command = "unset VUE_APP_SOCKET_ENDPOINT && yarn build:client"
